---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->



```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# electionViz

<!-- badges: start -->
<!-- badges: end -->

R package for visualizations of election (or poll) results as easy as adding `geom_electoral_building`.

## Installation

The development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("heike/electionViz")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example, include=FALSE}
library(electionViz)
library(tidyverse)

## basic example code
USelections %>% filter(year >= 2012) %>% glimpse()

elections <- USelections %>% 
  select(-office) %>%
  group_by(year, state) %>%
  mutate(percent = candidatevotes/totalvotes*100) %>%
  summarise(
    votes_dem = candidatevotes[party %in% c("democrat", "democratic-farmer-labor")],
    votes_rep = candidatevotes[party=="republican"],
    perc_dem = percent[party %in% c("democrat", "democratic-farmer-labor")],
    perc_rep = percent[party=="republican"],
    totalvotes = max(totalvotes),
    cand_dem = candidate[party %in% c("democrat", "democratic-farmer-labor")],
    cand_rep = candidate[party=="republican"],
    .groups = 'drop'
  )

# Merge geospatial and numerical information
ushex_plus <- ushex %>%
  left_join(elections, by="state")

centers <- ushex %>% select(centerX, centerY, abbr) %>% unique()
# Make a first chloropleth map
ushex_plus %>%
  filter(year >= 2012) %>%
  mutate(
    Election = year,
    Outcome = c("Republican", "Democrat")[as.numeric(perc_rep < perc_dem) + 1]) %>%
  ggplot() +
  geom_polygon(aes(fill =  Outcome, 
                   x = long, y = lat, group = group), 
               colour = "grey90", size = 0.1) +
  scale_fill_manual(values = c("darkblue", "darkred")) +
  geom_text(aes(x = centerX, y = centerY, label = abbr), 
            colour = "grey80", size = 3, data = centers) +
  theme_void() +
  coord_map() +
  facet_wrap(~Election, labeller = "label_both") +
  theme(legend.position = "bottom") 

```


